### ISSUE TITLE
Pinned Messages QA

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#3437]
@daniellekirkwood is moving the actions to other tickets so we can break this down into tasks for the team. Updated each section with the associated action. Questions in comments :) 

### Steps to reproduce

I spent some time with pinned messages to QA them.

### Outcome

- [x] **Developer Options Wording** Not relevant, this flag will disappear

- Currently: Pinned Events
- Should this turn into a user setting, the term _Events_ is more associated with a meeting event than with anything that can be pinned.
- Recommendation: Don't turn this into a user setting but make it default. If we use it as a setting, call it _Pinned Messages_

- [x] **Power Level** - feedback logged, https://github.com/element-hq/element-internal/issues/618

- Currently: requires Admin level
- this feels unfamiliar, as in WhatsApp anyone can pin a message in a group, not only an admin
- Recommendation: Would it make sense that the Admin setting would be something along the lines of "Only Admins can pin messages" with the default of "off"?

- [ ] **Visibility** - needs retesting, can't reproduce

- Currently: on EAX 0.5.3-nightly after getting admin rights and pinning the first message, the message is not visible in the room.
- Expected: message should be visible right away
- Workaround: leave the room and come back. Pinned message shows up then

- [x] **Show All** - verified in comments, it now works

- Currently: on EAX 0.5.3-nightl the "Show All" button doesn't work and does nothing
- Expected: list is shown
- Workaround: go to the room details and enter list there
- Update: now seems to work? Maybe something changed? Maybe flaky?
- Currently: the text for "show all" is taking a lot of attention and space in the pinned messages bar, which makes the pinned messages preview even less useful
- Recommendation: can we replace this text with a simple icon (like an eye or a zoom out or whatever)?

- [x] **Pinned Messages List Senders** - verified in comments, it works as expected, feedback logged https://github.com/element-hq/element-internal/issues/618

- Currently: Messages don't show sender
- Expected: Messages are displayed pretty much the same way they show in the timeline with a sender

- [x] **Pinned Messages List Action** Feedback logged https://github.com/element-hq/element-internal/issues/618

- Currently: Single tap on pinned messages does nothing
- Expected: View in timeline
- Workaround: Long tap to get context menu and tap "view in timeline" there

- [ ] **View in timeline Action** - needs further discussion (in Element)

- Currently: App jumps to timeline and scrolls around but not to the actual pinned message
- Expected: The pinned message is seen as the top message in the timeline
- Workaround: none

- [x] **German translation** https://github.com/element-hq/element-internal/issues/625

- Currently: pinned messages top bar says "1 of n Angepinnte Nachrichten"
- Expected: "1 of n angepinnte Nachrichten" (no capital A)
- Currently: headline of all messages view is "n pinned messages"
- Expected: "n angepinnte Nachrichten"
- Currently: pinned messages use "pin" and "unpin" in German. That's unusual at best.
- Expected: use WhatsApp translation "fixieren" for pin and "lösen" for unpin

### Your phone model

Pixel 8a

### Operating system version

Android 14

### Application version and app store

0.5.3-nightly

### Homeserver

element.io

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by daniellekirkwood** [comment]
> Developer Options Wording

Irrelevant, it will not be a flag for users. It will be on. They can choose not to use it

**Comment by daniellekirkwood** [comment]
> Power Level

Moderators and Administrators can pin messages. We've discussed changing the default access level but it is out of scope at this time. We cannot use WhatsApp for a benchmark in this case as WhatsApp limits the number of users in one room - we must be careful to not allow a spam vector. 

We've identified this as something we will keep an eye on and iterate on in the future. 

On Web, users may change the power setting so that all users in that room can pin a message. So this is non-blocking

**Comment by daniellekirkwood** [comment]
> Show All

@kongo09 can you confirm it works on the latest version? I think you may have tested this before it was complete. I believe the fix has landed

> Currently: the text for "show all" is taking a lot of attention and space in the pinned messages bar, which makes the pinned messages preview even less useful. Recommendation: can we replace this text with a simple icon (like an eye or a zoom out or whatever)?

Will add this to the feedback issue and discuss it with the team. It's not a blocker for launch.

**Comment by daniellekirkwood** [comment]
>  Pinned Messages List Senders Currently: Messages don't show sender

@kongo09 this should only be the case in DMs (rooms with one other person). Can you test and confirm please?

**Comment by kongo09** [comment]
> @kongo09 can you confirm it works on the latest version? I think you may have tested this before it was complete. I believe the fix has landed

tried again just now, et voila, it works

**Comment by kongo09** [comment]
> @kongo09 this should only be the case in DMs (rooms with one other person). Can you test and confirm please?

tried again just now and you're right, this works as expected

**Comment by daniellekirkwood** [comment]
> Visibility: Currently on EAX 0.5.3-nightly after getting admin rights and pinning the first message, the message is not visible in the room.

We can't reproduce this - we think it might have something to do with the 'hide on scroll' implementation. Would you test again and scroll in the room before leaving and coming back to see if that works?

If it doesn't, we will need more info on this one...

**Comment by daniellekirkwood** [comment]
> Pinned Messages List Action Currently: Single tap on pinned messages does nothing

Does Single tap on the timeline bring up the context menu?

**Comment by daniellekirkwood** [comment]
> View in timeline Action
> Currently: App jumps to timeline and scrolls around but not to the actual pinned message
> Expected: The pinned message is seen as the top message in the timeline

I believe we've used the same behaviour as when you link to a message so it shouldn't be right at the top. The message should have some sort of highlight on it though -- that's now an open task, it's not blocking to the first release but we'll try to get it in any way.

**Comment by daniellekirkwood** [comment]
Translations -- Thank you! Will ask the team to update!

**Comment by daniellekirkwood** [comment]
@kongo09 Will research but the banner already takes you to the message in the timeline so this feels duplicative to me. Also on iOS the Starred messages has a button that makes it clear that one-tap will take you somewhere... I don't think this is a blocker to launch, have added to the iteration feedback issue! Thanks

**Comment by kongo09** [comment]
I think we're talking past each other. The banner in the timeline (on Android) is also leading to some random place in the timeline, but I was talking about single tapping on a pinned message in the "all pinned messages" list

**Comment by daniellekirkwood** [comment]
You sent me a video and that's helped a lot - now working with the team how we address the pieces!

**Comment by bmarty** [comment]
Closed as stale issue. Feel free to open again if necessary.

**Comment by kongo09** [comment]
Testing again and two problems remain (and are reproducible):
- single tap in pinned messages list does nothing (instead of viewing in the timeline)
- pinning a message after scrolling the timeline up will not show the message header. It only shows once you scroll down again

tested on 25.02.0-nightly

**Comment by bmarty** [comment]
> single tap in pinned messages list does nothing (instead of viewing in the timeline)

This will interfere with the "view in fullscreen" click action when the pinned message is a media. Is it OK to have different treatment for media and text message on a click action (CC @daniellekirkwood )

> pinning a message after scrolling the timeline up will not show the message header. It only shows once you scroll down again

Handled by #4606

**Comment by daniellekirkwood** [comment]
No, I think the actions should be consistent... Are we still working on pinned messages?

**Comment by bmarty** [comment]
Let's close this old issue. Please open more specific issue about pinned message if something is not working as expected.
